<?php
	$default = "mm";
    $size = 35;
    $grav_url = "http://www.gravatar.com/avatar/".md5(strtolower(trim('tuxdirector@gmail.com')))."?d=".$default."&s=".$size;


	$ch = curl_init(); 
    curl_setopt($ch, CURLOPT_URL, 'http://localhost/ggs/api/comment'); 
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
    $result = curl_exec($ch); 
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE); 
    curl_close($ch); 
    $comments = json_decode($result, true);

    foreach ($comments as $comment) {

		$ch = curl_init(); 
	    curl_setopt($ch, CURLOPT_URL, 'http://localhost/ggs/api/login/getUserInfo'); 
        curl_setopt($ch, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['userId' => $comment['user_id']]));
	    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); 
	    $result   = curl_exec($ch); 
	    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE); 
	    curl_close($ch); 
	    $userInfo = json_decode($result, true);
	    $user = 'Anonymous';
	    
	    if ($userInfo) {
	    	$user =  $userInfo['firstname'] . ' ' . $userInfo['lastname'];
	    }
    ?>
	<div class="cmt-cnt">
	    <img src="<?php echo $grav_url; ?>" />
	    <div class="thecom">
	        <h5><?php echo $user; ?></h5><span data-utime="1371248446" class="com-dt"><?php echo $comment['date']; ?></span>
	        <br/>
	        <p>
	            <?php echo $comment['comment']; ?>
	        </p>
	    </div>
	</div>

	<? } ?>

